import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Box, Text, Heading, Image } from '@chakra-ui/react'

export default function Home() {
  const [nft, setNft] = useState([])
  const [metadata, setMetadata] = useState({})

  useEffect(() => {
    getNFTs()
  }, [])

  const getNFTs = async() => {
    const items = await fetch('https://deep-index.moralis.io/api/v2/0xaD031EeE55f595dF6Dbd61e9ef3B908FaD1B3671/nft?chain=eth&format=decimal&limit=10', {
      method: "GET",
      headers: {
        "X-API-Key": "Bp2sshSrgLB2QlKlkt0gzfTwSjdCWyyWgSF7CVtyIvtejQbNBXcrxAqlHT1W0Tyv",
        "Content-Type": "application/json"
      }
    })
    const res = await items.json()
    const meta = await res.result.map((r, i) => {
      const metadata = JSON.parse(r.metadata)
      return { ...r, metadata }
    })
    console.log(meta)
    setNft(meta)
  }

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>Fetching NFT</Heading>
      {
        nft.map((item, id) => (
          <Box>
            <Text key={id}>TOKEN ID: {item.token_id}</Text>
            <Text>NAME: {item.metadata && item.metadata.name}</Text>
            <Heading>Image: </Heading>
            <Image src={item.metadata && item.metadata.image} boxSize={200} />
          </Box>
        ))
      }
    </Box>
  )
}
